name: test_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  isolate_manager: 4.1.5
  dio: 5.4.1
  http: 1.2.1
  http_parser: 4.0.2
  json_serializable: 6.7.1
  hooks_riverpod: 2.4.10
  riverpod_annotation: 2.3.4
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  js:
  riverpod_generator: 2.3.11
  build_runner: 2.4.8

flutter:
  uses-material-design: true
